package com.tradespeople.model;

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private long id;
     private Shop shop;
     private User user;
     private String commenttext;
     private Date createddate;
     private Byte status;

    public Comment() {
    }

	
    public Comment(long id, Shop shop, User user) {
        this.id = id;
        this.shop = shop;
        this.user = user;
    }
    public Comment(long id, Shop shop, User user, String commenttext, Date createddate, Byte status) {
       this.id = id;
       this.shop = shop;
       this.user = user;
       this.commenttext = commenttext;
       this.createddate = createddate;
       this.status = status;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Shop getShop() {
        return this.shop;
    }
    
    public void setShop(Shop shop) {
        this.shop = shop;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCommenttext() {
        return this.commenttext;
    }
    
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


