package com.tradespeople.model;

import java.util.Date;

import com.tradespeople.common.api.BaseModel;

/**
 * Comment generated by hbm2java
 */
public class Comment extends BaseModel  implements java.io.Serializable {
	
	private static final long serialVersionUID = -4827751743188442452L;
	
	private Shop shop;
     private User user;
     private String commenttext;
     private Byte status;

    public Comment() {
    }

	
    public Comment(long id, Shop shop, User user) {
        this.setId(id);
        this.shop = shop;
        this.user = user;
    }
    public Comment(long id, Shop shop, User user, String commenttext, Date createddate, Byte status) {
       this.setId(id);
       this.shop = shop;
       this.user = user;
       this.commenttext = commenttext;
       this.setCreateddate(createddate);
       this.status = status;
    }
   
    public Shop getShop() {
        return this.shop;
    }
    
    public void setShop(Shop shop) {
        this.shop = shop;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCommenttext() {
        return this.commenttext;
    }
    
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

}


