package com.tradespeople.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tradespeople.common.api.BaseModel;


/**
 * Medialookup generated by hbm2java
 */
@Entity
@Table(name = "medialookup")
public class Medialookup extends BaseModel implements java.io.Serializable {

	private Media media;
	private Shop shop;
	private User user;
	private Byte status;
	private Date updateddate;

	public Medialookup() {
	}

	public Medialookup(long id, Media media) {
		this.id = id;
		this.media = media;
	}

	public Medialookup(long id, Media media, Shop shop, User user, Byte status,
			Date createddate, Date updateddate) {
		this.id = id;
		this.media = media;
		this.shop = shop;
		this.user = user;
		this.status = status;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDIAID", nullable = false)
	public Media getMedia() {
		return this.media;
	}

	public void setMedia(Media media) {
		this.media = media;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SHOPID")
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Updateddate", length = 0)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
