package com.tradespeople.model;

import java.util.Date;

/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private long id;
     private byte type;
     private String path;
     private Date createddate;
     private Date updateddate;
     private Byte status;
     private Long creatoruserid;
     private String description;

    public Media() {
    }

	
    public Media(long id, byte type, String path) {
        this.id = id;
        this.type = type;
        this.path = path;
    }
    public Media(long id, byte type, String path, Date createddate, Date updateddate, Byte status, Long creatoruserid, String description) {
       this.id = id;
       this.type = type;
       this.path = path;
       this.createddate = createddate;
       this.updateddate = updateddate;
       this.status = status;
       this.creatoruserid = creatoruserid;
       this.description = description;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public Date getUpdateddate() {
        return this.updateddate;
    }
    
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Long getCreatoruserid() {
        return this.creatoruserid;
    }
    
    public void setCreatoruserid(Long creatoruserid) {
        this.creatoruserid = creatoruserid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


