package com.tradespeople.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tradespeople.common.api.BaseModel;

/**
 * Role generated by hbm2java
 */
public class Role extends BaseModel implements java.io.Serializable {

	private String name;
	private Date updateddate;
	private Byte status;
	private Set userroles = new HashSet(0);

	public Role() {
	}

	public Role(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Role(long id, String name, Date createddate, Date updateddate,
			Byte status, Set userroles) {
		this.id = id;
		this.name = name;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.status = status;
		this.userroles = userroles;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Set getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set userroles) {
		this.userroles = userroles;
	}

}
