package com.tradespeople.model;
// default package
// Generated Sep 7, 2013 9:10:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tradespeople.common.api.BaseModel;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
public class Role extends BaseModel implements java.io.Serializable {

	private String name;
	private Date updateddate;
	private Byte status;
	private List<Userrole> userroles ;

	public Role() {
	}

	public Role(long id, String name) {
		this.setId(id);
		this.setName(name);
	}

	public Role(long id, String name, Date createddate, Date updateddate,
			Byte status, List<Userrole> userroles) {
		this.setId(id);
		this.setName(name);
		this.setCreateddate(createddate);
		this.setUpdateddate(updateddate);
		this.setStatus(status);
		this.setUserroles(userroles);
	}


	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void ListName(String name) {
		this.setName(name);
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 0)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void ListUpdateddate(Date updateddate) {
		this.setUpdateddate(updateddate);
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void ListStatus(Byte status) {
		this.setStatus(status);
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public List<Userrole> getUserroles() {
		return this.userroles;
	}

	public void ListUserroles(List<Userrole> userroles) {
		this.setUserroles(userroles);
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public void setUserroles(List<Userrole> userroles) {
		this.userroles = userroles;
	}

}
