package com.tradespeople.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tradespeople.common.api.BaseModel;

/**
 * Shopcategory generated by hbm2java
 */
public class Shopcategory extends BaseModel implements java.io.Serializable {

	private String name;
	private String mediapath;
	private Date updateddate;
	private Byte status;
	private Set shops = new HashSet(0);

	public Shopcategory() {
	}

	public Shopcategory(long id, String name, String mediapath) {
		this.id = id;
		this.name = name;
		this.mediapath = mediapath;
	}

	public Shopcategory(long id, String name, String mediapath,
			Date createddate, Date updateddate, Byte status, Set shops) {
		this.id = id;
		this.name = name;
		this.mediapath = mediapath;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.status = status;
		this.shops = shops;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMediapath() {
		return this.mediapath;
	}

	public void setMediapath(String mediapath) {
		this.mediapath = mediapath;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Set getShops() {
		return this.shops;
	}

	public void setShops(Set shops) {
		this.shops = shops;
	}

}
