package com.tradespeople.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tradespeople.common.api.BaseModel;

/**
 * Shop generated by hbm2java
 */
@Entity
@Table(name = "shop")
public class Shop extends BaseModel implements java.io.Serializable {

	private User user;
	private Shopcategory shopcategory;
	private String name;
	private String address;
	private String district;
	private String city;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private Byte status;
	private String about;
	private Date updateddate;
	private Set<Medialookup> medialookups = new HashSet<Medialookup>(0);
	private Set<Shoptag> shoptags = new HashSet<Shoptag>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Shop() {
	}

	public Shop(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Shop(long id, User user, Shopcategory shopcategory, String name,
			String address, String district, String city, BigDecimal latitude,
			BigDecimal longitude, Byte status, String about, Date createddate,
			Date updateddate, Set<Medialookup> medialookups,
			Set<Shoptag> shoptags, Set<Comment> comments) {
		this.id = id;
		this.user = user;
		this.shopcategory = shopcategory;
		this.name = name;
		this.address = address;
		this.district = district;
		this.city = city;
		this.latitude = latitude;
		this.longitude = longitude;
		this.status = status;
		this.about = about;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.medialookups = medialookups;
		this.shoptags = shoptags;
		this.comments = comments;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATORUSERID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORYID")
	public Shopcategory getShopcategory() {
		return this.shopcategory;
	}

	public void setShopcategory(Shopcategory shopcategory) {
		this.shopcategory = shopcategory;
	}

	@Column(name = "NAME", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "DISTRICT", length = 50)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "CITY", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "LATITUDE", precision = 10, scale = 7)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", precision = 10, scale = 7)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "ABOUT", length = 65535)
	public String getAbout() {
		return this.about;
	}

	public void setAbout(String about) {
		this.about = about;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 0)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shop")
	public Set<Medialookup> getMedialookups() {
		return this.medialookups;
	}

	public void setMedialookups(Set<Medialookup> medialookups) {
		this.medialookups = medialookups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shop")
	public Set<Shoptag> getShoptags() {
		return this.shoptags;
	}

	public void setShoptags(Set<Shoptag> shoptags) {
		this.shoptags = shoptags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shop")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
