package com.tradespeople.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tradespeople.common.api.BaseModel;


/**
 * Shoptag generated by hbm2java
 */
@Entity
@Table(name = "shoptag")
public class Shoptag extends BaseModel implements java.io.Serializable {

	private Shop shop;
	private Tag tag;
	private Date updateddate;

	public Shoptag() {
	}

	public Shoptag(Long id, Shop shop, Tag tag) {
		this.id = id;
		this.shop = shop;
		this.tag = tag;
	}

	public Shoptag(Long id, Shop shop, Tag tag, Date createddate,
			Date updateddate) {
		this.id = id;
		this.shop = shop;
		this.tag = tag;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SHOPID", nullable = false)
	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAGID", nullable = false)
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 0)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
