package com.tradespeople.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Shop generated by hbm2java
 */
public class Shop  implements java.io.Serializable {


     private long id;
     private User user;
     private Shopcategory shopcategory;
     private String name;
     private String address;
     private String district;
     private String city;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private Byte status;
     private String about;
     private Date createddate;
     private Date updateddate;
     private Set shoptags = new HashSet(0);
     private Set comments = new HashSet(0);

    public Shop() {
    }

	
    public Shop(long id, String name) {
        this.id = id;
        this.name = name;
    }
    public Shop(long id, User user, Shopcategory shopcategory, String name, String address, String district, String city, BigDecimal latitude, BigDecimal longitude, Byte status, String about, Date createddate, Date updateddate, Set shoptags, Set comments) {
       this.id = id;
       this.user = user;
       this.shopcategory = shopcategory;
       this.name = name;
       this.address = address;
       this.district = district;
       this.city = city;
       this.latitude = latitude;
       this.longitude = longitude;
       this.status = status;
       this.about = about;
       this.createddate = createddate;
       this.updateddate = updateddate;
       this.shoptags = shoptags;
       this.comments = comments;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Shopcategory getShopcategory() {
        return this.shopcategory;
    }
    
    public void setShopcategory(Shopcategory shopcategory) {
        this.shopcategory = shopcategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public Date getUpdateddate() {
        return this.updateddate;
    }
    
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }
    public Set getShoptags() {
        return this.shoptags;
    }
    
    public void setShoptags(Set shoptags) {
        this.shoptags = shoptags;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


