package com.tradespeople.model;
// default package
// Generated Sep 7, 2013 9:10:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tradespeople.common.api.BaseModel;

/**
 * Shopcategory generated by hbm2java
 */
@Entity
@Table(name = "shopcategory")
public class Shopcategory extends BaseModel implements java.io.Serializable {

	public void setName(String name) {
		this.name = name;
	}

	public void setMediapath(String mediapath) {
		this.mediapath = mediapath;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public void setShops(List<Shop> shops) {
		this.shops = shops;
	}

	private String name;
	private String mediapath;
	private Date updateddate;
	private Byte status;
	private List<Shop> shops = new ArrayList<Shop>(0);

	public Shopcategory() {
	}

	public Shopcategory(long id, String name, String mediapath) {
		this.id = id;
		this.name = name;
		this.mediapath = mediapath;
	}

	public Shopcategory(long id, String name, String mediapath,
			Date createddate, Date updateddate, Byte status, List<Shop> shops) {
		this.id = id;
		this.name = name;
		this.mediapath = mediapath;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.status = status;
		this.shops = shops;
	}

	public void ListId(long id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void ListName(String name) {
		this.name = name;
	}

	@Column(name = "MEDIAPATH", nullable = false, length = 500)
	public String getMediapath() {
		return this.mediapath;
	}

	public void ListMediapath(String mediapath) {
		this.mediapath = mediapath;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 0)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void ListUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void ListStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopcategory")
	public List<Shop> getShops() {
		return this.shops;
	}

	public void ListShops(List<Shop> shops) {
		this.shops = shops;
	}

}
