package com.tradespeople.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private long id;
     private String name;
     private Date createddate;
     private Date updateddate;
     private Set shoptags = new HashSet(0);

    public Tag() {
    }

	
    public Tag(long id, String name) {
        this.id = id;
        this.name = name;
    }
    public Tag(long id, String name, Date createddate, Date updateddate, Set shoptags) {
       this.id = id;
       this.name = name;
       this.createddate = createddate;
       this.updateddate = updateddate;
       this.shoptags = shoptags;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public Date getUpdateddate() {
        return this.updateddate;
    }
    
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }
    public Set getShoptags() {
        return this.shoptags;
    }
    
    public void setShoptags(Set shoptags) {
        this.shoptags = shoptags;
    }




}


