package com.tradespeople.model;
// default package
// Generated Sep 7, 2013 9:10:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tradespeople.common.api.BaseModel;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag")
public class Tag extends BaseModel implements java.io.Serializable {

	private String name;
	private Date updateddate;
	private List<Shoptag> shoptags = new ArrayList<Shoptag>(0);

	public Tag() {
	}

	public Tag(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Tag(long id, String name, Date createddate, Date updateddate,
			List<Shoptag> shoptags) {
		this.id = id;
		this.name = name;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.shoptags = shoptags;
	}
	
	public void setName(String name) {
		this.name = name;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public void setShoptags(List<Shoptag> shoptags) {
		this.shoptags = shoptags;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void ListName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 0)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void ListUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public List<Shoptag> getShoptags() {
		return this.shoptags;
	}

	public void ListShoptags(List<Shoptag> shoptags) {
		this.shoptags = shoptags;
	}

}
