package com.tradespeople.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tradespeople.common.api.BaseModel;

/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name = "userrole")
public class Userrole extends BaseModel implements java.io.Serializable {

	private Role role;
	private User user;
	private Date updateddate;
	private Byte status;

	public Userrole() {
	}

	public Userrole(long id, Role role, User user) {
		this.id = id;
		this.role = role;
		this.user = user;
	}

	public Userrole(long id, Role role, User user, Date createddate,
			Date updateddate, Byte status) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLEID", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 0)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
