package com.tradespeople.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import com.tradespeople.common.api.BaseModel;

/**
 * User generated by hbm2java
 */
@Entity
public class User  extends BaseModel   implements java.io.Serializable {

     private String username;
     private String password;
     private String token;
     private Date updateddate;
     private Byte status;
     private Set comments = new HashSet(0);
     private Set shops = new HashSet(0);
     private Set userroles = new HashSet(0);

    public User() {
    }

	
    public User(long id, String username) {
        this.id = id;
        this.username = username;
    }
    public User(long id, String username, String password, String token, Date createddate, Date updateddate, Byte status, Set comments, Set shops, Set userroles) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.token = token;
       this.createddate = createddate;
       this.updateddate = updateddate;
       this.status = status;
       this.comments = comments;
       this.shops = shops;
       this.userroles = userroles;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getUpdateddate() {
        return this.updateddate;
    }
    
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getShops() {
        return this.shops;
    }
    
    public void setShops(Set shops) {
        this.shops = shops;
    }
    public Set getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(Set userroles) {
        this.userroles = userroles;
    }




}


