package com.tradespeople.model;

import java.util.Date;

import com.tradespeople.common.api.BaseModel;

/**
 * Userrole generated by hbm2java
 */
public class Userrole extends BaseModel implements java.io.Serializable {

	private Role role;
	private User user;
	private Date updateddate;
	private Byte status;

	public Userrole() {
	}

	public Userrole(long id, Role role, User user) {
		this.id = id;
		this.role = role;
		this.user = user;
	}

	public Userrole(long id, Role role, User user, Date createddate,
			Date updateddate, Byte status) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.status = status;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
